const LogCodes = {
  // Generic log codes
  REQUEST_RECEIVED: "REQUEST_RECEIVED",
  REQUEST_RESPONSE: "REQUEST_RESPONSE",
  ERROR_RESPONSE: "ERROR_RESPONSE",
  AUTHENTICATED_REQUEST: "AUTHENTICATED_REQUEST",
  UNAUTHENTICATED_REQUEST: "UNAUTHENTICATED_REQUEST",

  // Log codes for post module
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",
  CREATE_POST_ERROR: "CREATE_POST_ERROR",
  GET_POST_ERROR: "GET_POST_ERROR",
  UPDATE_POST_ERROR: "UPDATE_POST_ERROR",
  DELETE_POST_ERROR: "DELETE_POST_ERROR",

  // Log codes for comment module
  ADD_COMMENT_ERROR: "ADD_COMMENT_ERROR",
  FETCH_COMMENTS_ERROR: "FETCH_COMMENTS_ERROR",
  UPDATE_COMMENT_ERROR: "UPDATE_COMMENT_ERROR",
  DELETE_COMMENT_ERROR: "DELETE_COMMENT_ERROR",
};

export default LogCodes;
